name: validate-ent

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Generate Ent code
        run: |
          go run ent/generate.go