// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// CountryLocation is the predicate function for countrylocation builders.
type CountryLocation func(*sql.Selector)
